/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const DealStage = IDL.Variant({
  'new' : IDL.Null,
  'won' : IDL.Null,
  'lost' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const Deal = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'value' : IDL.Float64,
  'stage' : DealStage,
  'customerId' : IDL.Nat,
});
export const LeadStatus = IDL.Variant({
  'new' : IDL.Null,
  'lost' : IDL.Null,
  'contacted' : IDL.Null,
  'converted' : IDL.Null,
  'qualified' : IDL.Null,
});
export const Lead = IDL.Record({
  'id' : IDL.Nat,
  'status' : LeadStatus,
  'contact' : IDL.Text,
  'name' : IDL.Text,
  'notes' : IDL.Text,
  'reminderIds' : IDL.Vec(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
  'profileComplete' : IDL.Bool,
});
export const ApprovalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const UserApprovalInfo = IDL.Record({
  'status' : ApprovalStatus,
  'principal' : IDL.Principal,
});
export const CreateUserStatus = IDL.Variant({
  'created' : IDL.Null,
  'createdFirstAdmin' : IDL.Null,
  'alreadyExists' : IDL.Null,
});
export const OTPVerificationResult = IDL.Variant({
  'expired' : IDL.Null,
  'invalid' : IDL.Null,
  'success' : CreateUserStatus,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addDeal' : IDL.Func([IDL.Text, IDL.Float64, IDL.Nat, DealStage], [Deal], []),
  'addLead' : IDL.Func([IDL.Text, IDL.Text, LeadStatus, IDL.Text], [Lead], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteDeal' : IDL.Func([IDL.Nat], [], []),
  'deleteLead' : IDL.Func([IDL.Nat], [], []),
  'generateOTP' : IDL.Func([IDL.Text], [IDL.Text], []),
  'getAllDeals' : IDL.Func([], [IDL.Vec(Deal)], ['query']),
  'getAllLeads' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDeal' : IDL.Func([IDL.Nat], [IDL.Opt(Deal)], ['query']),
  'getDealsByStage' : IDL.Func([DealStage], [IDL.Vec(Deal)], ['query']),
  'getLead' : IDL.Func([IDL.Nat], [IDL.Opt(Lead)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
  'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
  'moveDealStage' : IDL.Func([IDL.Nat, DealStage], [Deal], []),
  'requestApproval' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null })],
      [],
    ),
  'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
  'updateDeal' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Float64, IDL.Nat, DealStage],
      [Deal],
      [],
    ),
  'updateLead' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, LeadStatus, IDL.Text],
      [Lead],
      [],
    ),
  'verifyOTP' : IDL.Func([IDL.Text, IDL.Text], [OTPVerificationResult], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const DealStage = IDL.Variant({
    'new' : IDL.Null,
    'won' : IDL.Null,
    'lost' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const Deal = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'value' : IDL.Float64,
    'stage' : DealStage,
    'customerId' : IDL.Nat,
  });
  const LeadStatus = IDL.Variant({
    'new' : IDL.Null,
    'lost' : IDL.Null,
    'contacted' : IDL.Null,
    'converted' : IDL.Null,
    'qualified' : IDL.Null,
  });
  const Lead = IDL.Record({
    'id' : IDL.Nat,
    'status' : LeadStatus,
    'contact' : IDL.Text,
    'name' : IDL.Text,
    'notes' : IDL.Text,
    'reminderIds' : IDL.Vec(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
    'profileComplete' : IDL.Bool,
  });
  const ApprovalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const UserApprovalInfo = IDL.Record({
    'status' : ApprovalStatus,
    'principal' : IDL.Principal,
  });
  const CreateUserStatus = IDL.Variant({
    'created' : IDL.Null,
    'createdFirstAdmin' : IDL.Null,
    'alreadyExists' : IDL.Null,
  });
  const OTPVerificationResult = IDL.Variant({
    'expired' : IDL.Null,
    'invalid' : IDL.Null,
    'success' : CreateUserStatus,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addDeal' : IDL.Func(
        [IDL.Text, IDL.Float64, IDL.Nat, DealStage],
        [Deal],
        [],
      ),
    'addLead' : IDL.Func(
        [IDL.Text, IDL.Text, LeadStatus, IDL.Text],
        [Lead],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteDeal' : IDL.Func([IDL.Nat], [], []),
    'deleteLead' : IDL.Func([IDL.Nat], [], []),
    'generateOTP' : IDL.Func([IDL.Text], [IDL.Text], []),
    'getAllDeals' : IDL.Func([], [IDL.Vec(Deal)], ['query']),
    'getAllLeads' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDeal' : IDL.Func([IDL.Nat], [IDL.Opt(Deal)], ['query']),
    'getDealsByStage' : IDL.Func([DealStage], [IDL.Vec(Deal)], ['query']),
    'getLead' : IDL.Func([IDL.Nat], [IDL.Opt(Lead)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
    'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
    'moveDealStage' : IDL.Func([IDL.Nat, DealStage], [Deal], []),
    'requestApproval' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null })],
        [],
      ),
    'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
    'updateDeal' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Float64, IDL.Nat, DealStage],
        [Deal],
        [],
      ),
    'updateLead' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, LeadStatus, IDL.Text],
        [Lead],
        [],
      ),
    'verifyOTP' : IDL.Func([IDL.Text, IDL.Text], [OTPVerificationResult], []),
  });
};

export const init = ({ IDL }) => { return []; };