/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export type CreateUserStatus = { 'created' : null } |
  { 'createdFirstAdmin' : null } |
  { 'alreadyExists' : null };
export interface Deal {
  'id' : bigint,
  'title' : string,
  'value' : number,
  'stage' : DealStage,
  'customerId' : bigint,
}
export type DealStage = { 'new' : null } |
  { 'won' : null } |
  { 'lost' : null } |
  { 'inProgress' : null };
export interface Lead {
  'id' : bigint,
  'status' : LeadStatus,
  'contact' : string,
  'name' : string,
  'notes' : string,
  'reminderIds' : Array<bigint>,
}
export type LeadStatus = { 'new' : null } |
  { 'lost' : null } |
  { 'contacted' : null } |
  { 'converted' : null } |
  { 'qualified' : null };
export type OTPVerificationResult = { 'expired' : null } |
  { 'invalid' : null } |
  { 'success' : CreateUserStatus };
export interface UserApprovalInfo {
  'status' : ApprovalStatus,
  'principal' : Principal,
}
export interface UserProfile {
  'name' : string,
  'email' : string,
  'phone' : string,
  'profileComplete' : boolean,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addDeal' : ActorMethod<[string, number, bigint, DealStage], Deal>,
  'addLead' : ActorMethod<[string, string, LeadStatus, string], Lead>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteDeal' : ActorMethod<[bigint], undefined>,
  'deleteLead' : ActorMethod<[bigint], undefined>,
  'generateOTP' : ActorMethod<[string], string>,
  'getAllDeals' : ActorMethod<[], Array<Deal>>,
  'getAllLeads' : ActorMethod<[], Array<Lead>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDeal' : ActorMethod<[bigint], [] | [Deal]>,
  'getDealsByStage' : ActorMethod<[DealStage], Array<Deal>>,
  'getLead' : ActorMethod<[bigint], [] | [Lead]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerApproved' : ActorMethod<[], boolean>,
  'listApprovals' : ActorMethod<[], Array<UserApprovalInfo>>,
  'moveDealStage' : ActorMethod<[bigint, DealStage], Deal>,
  'requestApproval' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<
    [string, string, string],
    { 'ok' : null }
  >,
  'setApproval' : ActorMethod<[Principal, ApprovalStatus], undefined>,
  'updateDeal' : ActorMethod<[bigint, string, number, bigint, DealStage], Deal>,
  'updateLead' : ActorMethod<
    [bigint, string, string, LeadStatus, string],
    Lead
  >,
  'verifyOTP' : ActorMethod<[string, string], OTPVerificationResult>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];