/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Customer = IDL.Record({
  'id' : IDL.Nat,
  'latitude' : IDL.Float64,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'longitude' : IDL.Float64,
  'address' : IDL.Text,
  'phone' : IDL.Text,
  'reminderIds' : IDL.Vec(IDL.Nat),
});
export const DealStage = IDL.Variant({
  'new' : IDL.Null,
  'won' : IDL.Null,
  'lost' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const Deal = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'value' : IDL.Float64,
  'stage' : DealStage,
  'customerId' : IDL.Nat,
});
export const LeadStatus = IDL.Variant({
  'new' : IDL.Null,
  'lost' : IDL.Null,
  'contacted' : IDL.Null,
  'converted' : IDL.Null,
  'qualified' : IDL.Null,
});
export const Lead = IDL.Record({
  'id' : IDL.Nat,
  'status' : LeadStatus,
  'contact' : IDL.Text,
  'name' : IDL.Text,
  'notes' : IDL.Text,
  'reminderIds' : IDL.Vec(IDL.Nat),
});
export const Time = IDL.Int;
export const Reminder = IDL.Record({
  'id' : IDL.Nat,
  'note' : IDL.Text,
  'dueDate' : Time,
  'isOverdue' : IDL.Bool,
});
export const ProjectStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'inProgress' : IDL.Null,
  'onHold' : IDL.Null,
});
export const SiteSurvey = IDL.Record({
  'date' : Time,
  'notes' : IDL.Text,
  'surveyorName' : IDL.Text,
});
export const SolarProject = IDL.Record({
  'id' : IDL.Nat,
  'siteSurvey' : SiteSurvey,
  'installationStatus' : ProjectStatus,
  'systemSizeKW' : IDL.Float64,
  'customerId' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const ApprovalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const UserApprovalInfo = IDL.Record({
  'status' : ApprovalStatus,
  'principal' : IDL.Principal,
});
export const CreateUserStatus = IDL.Variant({
  'created' : IDL.Null,
  'createdFirstAdmin' : IDL.Null,
  'alreadyExists' : IDL.Null,
});
export const OTPVerificationResult = IDL.Variant({
  'expired' : IDL.Null,
  'invalid' : IDL.Null,
  'success' : CreateUserStatus,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCustomer' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Float64, IDL.Float64],
      [Customer],
      [],
    ),
  'addDeal' : IDL.Func([IDL.Text, IDL.Float64, IDL.Nat, DealStage], [Deal], []),
  'addLead' : IDL.Func([IDL.Text, IDL.Text, LeadStatus, IDL.Text], [Lead], []),
  'addReminder' : IDL.Func([Time, IDL.Text], [Reminder], []),
  'addSolarProject' : IDL.Func(
      [IDL.Nat, IDL.Float64, ProjectStatus, IDL.Text, IDL.Text, Time],
      [SolarProject],
      [],
    ),
  'approveUser' : IDL.Func([IDL.Principal], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteCustomer' : IDL.Func([IDL.Nat], [], []),
  'deleteDeal' : IDL.Func([IDL.Nat], [], []),
  'deleteLead' : IDL.Func([IDL.Nat], [], []),
  'deleteReminder' : IDL.Func([IDL.Nat], [], []),
  'deleteSolarProject' : IDL.Func([IDL.Nat], [], []),
  'generateOTP' : IDL.Func([IDL.Text], [IDL.Text], []),
  'getAllCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
  'getAllDeals' : IDL.Func([], [IDL.Vec(Deal)], ['query']),
  'getAllLeads' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
  'getAllReminders' : IDL.Func([], [IDL.Vec(Reminder)], ['query']),
  'getAllSolarProjects' : IDL.Func([], [IDL.Vec(SolarProject)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCustomer' : IDL.Func([IDL.Nat], [IDL.Opt(Customer)], ['query']),
  'getCustomerProjects' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(SolarProject)],
      ['query'],
    ),
  'getDashboardStats' : IDL.Func(
      [],
      [
        IDL.Record({
          'totalLeads' : IDL.Nat,
          'totalRevenue' : IDL.Float64,
          'totalCustomers' : IDL.Nat,
          'totalDeals' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getDeal' : IDL.Func([IDL.Nat], [IDL.Opt(Deal)], ['query']),
  'getDealsByStage' : IDL.Func([DealStage], [IDL.Vec(Deal)], ['query']),
  'getFilteredReminders' : IDL.Func([IDL.Bool], [IDL.Vec(Reminder)], ['query']),
  'getLead' : IDL.Func([IDL.Nat], [IDL.Opt(Lead)], ['query']),
  'getOverdueReminders' : IDL.Func([], [IDL.Vec(Reminder)], ['query']),
  'getPendingApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
  'getProjectCountByStatus' : IDL.Func(
      [],
      [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
      ['query'],
    ),
  'getSolarProject' : IDL.Func([IDL.Nat], [IDL.Opt(SolarProject)], ['query']),
  'getSuperAdminPrincipal' : IDL.Func([], [IDL.Opt(IDL.Principal)], ['query']),
  'getUpcomingReminders' : IDL.Func([Time], [IDL.Vec(Reminder)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
  'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
  'markReminderOverdue' : IDL.Func([IDL.Nat], [], []),
  'moveDealStage' : IDL.Func([IDL.Nat, DealStage], [Deal], []),
  'rejectUser' : IDL.Func([IDL.Principal], [], []),
  'requestApproval' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null })],
      [],
    ),
  'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
  'updateCustomer' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Float64,
      ],
      [Customer],
      [],
    ),
  'updateDeal' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Float64, IDL.Nat, DealStage],
      [Deal],
      [],
    ),
  'updateLead' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, LeadStatus, IDL.Text],
      [Lead],
      [],
    ),
  'updateProjectStatus' : IDL.Func(
      [IDL.Nat, ProjectStatus],
      [SolarProject],
      [],
    ),
  'updateReminder' : IDL.Func([IDL.Nat, Time, IDL.Text], [Reminder], []),
  'updateSolarProject' : IDL.Func(
      [IDL.Nat, IDL.Float64, ProjectStatus, IDL.Text, IDL.Text, Time],
      [SolarProject],
      [],
    ),
  'verifyOTP' : IDL.Func([IDL.Text, IDL.Text], [OTPVerificationResult], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Customer = IDL.Record({
    'id' : IDL.Nat,
    'latitude' : IDL.Float64,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'longitude' : IDL.Float64,
    'address' : IDL.Text,
    'phone' : IDL.Text,
    'reminderIds' : IDL.Vec(IDL.Nat),
  });
  const DealStage = IDL.Variant({
    'new' : IDL.Null,
    'won' : IDL.Null,
    'lost' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const Deal = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'value' : IDL.Float64,
    'stage' : DealStage,
    'customerId' : IDL.Nat,
  });
  const LeadStatus = IDL.Variant({
    'new' : IDL.Null,
    'lost' : IDL.Null,
    'contacted' : IDL.Null,
    'converted' : IDL.Null,
    'qualified' : IDL.Null,
  });
  const Lead = IDL.Record({
    'id' : IDL.Nat,
    'status' : LeadStatus,
    'contact' : IDL.Text,
    'name' : IDL.Text,
    'notes' : IDL.Text,
    'reminderIds' : IDL.Vec(IDL.Nat),
  });
  const Time = IDL.Int;
  const Reminder = IDL.Record({
    'id' : IDL.Nat,
    'note' : IDL.Text,
    'dueDate' : Time,
    'isOverdue' : IDL.Bool,
  });
  const ProjectStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'inProgress' : IDL.Null,
    'onHold' : IDL.Null,
  });
  const SiteSurvey = IDL.Record({
    'date' : Time,
    'notes' : IDL.Text,
    'surveyorName' : IDL.Text,
  });
  const SolarProject = IDL.Record({
    'id' : IDL.Nat,
    'siteSurvey' : SiteSurvey,
    'installationStatus' : ProjectStatus,
    'systemSizeKW' : IDL.Float64,
    'customerId' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const ApprovalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const UserApprovalInfo = IDL.Record({
    'status' : ApprovalStatus,
    'principal' : IDL.Principal,
  });
  const CreateUserStatus = IDL.Variant({
    'created' : IDL.Null,
    'createdFirstAdmin' : IDL.Null,
    'alreadyExists' : IDL.Null,
  });
  const OTPVerificationResult = IDL.Variant({
    'expired' : IDL.Null,
    'invalid' : IDL.Null,
    'success' : CreateUserStatus,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCustomer' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Float64, IDL.Float64],
        [Customer],
        [],
      ),
    'addDeal' : IDL.Func(
        [IDL.Text, IDL.Float64, IDL.Nat, DealStage],
        [Deal],
        [],
      ),
    'addLead' : IDL.Func(
        [IDL.Text, IDL.Text, LeadStatus, IDL.Text],
        [Lead],
        [],
      ),
    'addReminder' : IDL.Func([Time, IDL.Text], [Reminder], []),
    'addSolarProject' : IDL.Func(
        [IDL.Nat, IDL.Float64, ProjectStatus, IDL.Text, IDL.Text, Time],
        [SolarProject],
        [],
      ),
    'approveUser' : IDL.Func([IDL.Principal], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteCustomer' : IDL.Func([IDL.Nat], [], []),
    'deleteDeal' : IDL.Func([IDL.Nat], [], []),
    'deleteLead' : IDL.Func([IDL.Nat], [], []),
    'deleteReminder' : IDL.Func([IDL.Nat], [], []),
    'deleteSolarProject' : IDL.Func([IDL.Nat], [], []),
    'generateOTP' : IDL.Func([IDL.Text], [IDL.Text], []),
    'getAllCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
    'getAllDeals' : IDL.Func([], [IDL.Vec(Deal)], ['query']),
    'getAllLeads' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
    'getAllReminders' : IDL.Func([], [IDL.Vec(Reminder)], ['query']),
    'getAllSolarProjects' : IDL.Func([], [IDL.Vec(SolarProject)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCustomer' : IDL.Func([IDL.Nat], [IDL.Opt(Customer)], ['query']),
    'getCustomerProjects' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(SolarProject)],
        ['query'],
      ),
    'getDashboardStats' : IDL.Func(
        [],
        [
          IDL.Record({
            'totalLeads' : IDL.Nat,
            'totalRevenue' : IDL.Float64,
            'totalCustomers' : IDL.Nat,
            'totalDeals' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getDeal' : IDL.Func([IDL.Nat], [IDL.Opt(Deal)], ['query']),
    'getDealsByStage' : IDL.Func([DealStage], [IDL.Vec(Deal)], ['query']),
    'getFilteredReminders' : IDL.Func(
        [IDL.Bool],
        [IDL.Vec(Reminder)],
        ['query'],
      ),
    'getLead' : IDL.Func([IDL.Nat], [IDL.Opt(Lead)], ['query']),
    'getOverdueReminders' : IDL.Func([], [IDL.Vec(Reminder)], ['query']),
    'getPendingApprovals' : IDL.Func(
        [],
        [IDL.Vec(UserApprovalInfo)],
        ['query'],
      ),
    'getProjectCountByStatus' : IDL.Func(
        [],
        [IDL.Nat, IDL.Nat, IDL.Nat, IDL.Nat],
        ['query'],
      ),
    'getSolarProject' : IDL.Func([IDL.Nat], [IDL.Opt(SolarProject)], ['query']),
    'getSuperAdminPrincipal' : IDL.Func(
        [],
        [IDL.Opt(IDL.Principal)],
        ['query'],
      ),
    'getUpcomingReminders' : IDL.Func([Time], [IDL.Vec(Reminder)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
    'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
    'markReminderOverdue' : IDL.Func([IDL.Nat], [], []),
    'moveDealStage' : IDL.Func([IDL.Nat, DealStage], [Deal], []),
    'rejectUser' : IDL.Func([IDL.Principal], [], []),
    'requestApproval' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null })],
        [],
      ),
    'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
    'updateCustomer' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
        ],
        [Customer],
        [],
      ),
    'updateDeal' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Float64, IDL.Nat, DealStage],
        [Deal],
        [],
      ),
    'updateLead' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, LeadStatus, IDL.Text],
        [Lead],
        [],
      ),
    'updateProjectStatus' : IDL.Func(
        [IDL.Nat, ProjectStatus],
        [SolarProject],
        [],
      ),
    'updateReminder' : IDL.Func([IDL.Nat, Time, IDL.Text], [Reminder], []),
    'updateSolarProject' : IDL.Func(
        [IDL.Nat, IDL.Float64, ProjectStatus, IDL.Text, IDL.Text, Time],
        [SolarProject],
        [],
      ),
    'verifyOTP' : IDL.Func([IDL.Text, IDL.Text], [OTPVerificationResult], []),
  });
};

export const init = ({ IDL }) => { return []; };